# Generated by Django 5.2.3 on 2025-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_populate_blood_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ['name'], 'verbose_name': 'Ալերգիա', 'verbose_name_plural': 'Ալերգիաներ'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['name'], 'verbose_name': 'Հիվանդություն', 'verbose_name_plural': 'Հիվանդություններ'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name'], 'verbose_name': 'Դեղամիջոց', 'verbose_name_plural': 'Դեղամիջոցներ'},
        ),
        migrations.AlterModelOptions(
            name='surgery',
            options={'ordering': ['name'], 'verbose_name': 'Վիրահատություն', 'verbose_name_plural': 'Վիրահատություններ'},
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Անվանում'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='group_name',
            field=models.CharField(max_length=11, unique=True, verbose_name='Խմբի անվանում'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Անվանում'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Անվանում'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Անվանում'),
        ),
    ]
